#if !defined(_GAINER_CONTROL_H)
#define _GAINER_CONTROL_H

enum GainerCtlDispids {
    // ActiveX
    DISPID_VISIBLE = 10,
    // methods
    DISPID_OPEN = 20,
    DISPID_CLOSE,
    DISPID_WAIT,
    // Configuration
    DISPID_CONFIGURATION,
    // I/O
    DISPID_SET_ALLDIGITALOUTPUTS,
    DISPID_SET_SPECIDIFEDDIGITALOUTPUT,
    DISPID_GET_ALLDIGITALINPUTS,
    DISPID_EXIT_CONTINOUS_MODE,
    DISPID_SET_SENSITIVITY,
    DISPID_SET_ALLANALOGOUTPUTS,
    DISPID_SET_SPECIFIEDANALOGOUTPUT,
    DISPID_SET_SPECIFIEDANALOGOUTPUT_BY_ROW,
    DISPID_GET_ALLANALOGINPUTS,
    DISPID_GET_SPECIFIEDANALOGINPUT,
    DISPID_SET_AIN_SAMPLINGMODE,
    // LED
    DISPID_LED,
    // PGA
    DISPID_PGA,
    // Misc.
    DISPID_REBOOT,
    DISPID_VERBOSE,
    DISPID_VERSION,
};

#endif
